### ISSUE TITLE
Build failure with 'mvn install'

### ISSUE THREAD

**Issue by jpt1016** [seppinho/mutation-server#20]
First, I'm wondering if building and installing with maven enables the other steps of the pipeline for local use, specifically the align tool? Or is analyse-local the only locally available step? 

Also I tried building with 'mvn install' and there were 5 failed tests resulting in a build failure: 
Failed tests:   AlignmentPETest(genepi.mut.steps.MutationServerTest)
  AlignmentSETest(genepi.mut.steps.MutationServerTest)
  SortTestPE(genepi.mut.steps.MutationServerTest)
  SortTestSE(genepi.mut.steps.MutationServerTest)
  PileupFromFastqTest(genepi.mut.steps.MutationServerTest)

**Comment by seppinho** [comment]
hi,
only the "analyse-local" tool is available offline.
Regarding the build failure. Can you double check if you have you are using the latest from github? Our daily integration test works: 
https://travis-ci.org/seppinho/mutation-server
